### PR TITLE
WIP: Add Cattle orchestrator

### PR DESCRIPTION
**Pull request by cryptobioz**

### CODE REVIEW

**Comment by mcanevet** [comment]
Great work! Thanks.
From my point of view it can be merged as it should not break anything.
What do you think @raphink ?

**Comment by mcanevet** [comment]
Maybe we should try this branch in a multi-host environment with a volume in environment scope and a scaled service before merging. I have one or two issues in mind that can occur.

**Comment by cryptobioz** [comment]
I agree, even if it doesn't break anything, we should test it in a real environment before merging.

**Comment by mcanevet** [comment]
The only issue I can see so far is that the target does not contain anymore the name of the node hosting the volume, but only the name of the node hosting the bivac manager. So if we have the same volume on multiple hosts, they will be backed up in the same place.

**Pull request merged**
