### PR TITLE
feat(network): implement docker network

### PR DESCRIPTION
**Pull request by majklovec**

### CODE REVIEW

**Comment by majklovec** [comment]
https://github.com/camptocamp/bivac/pull/202

**Comment by cryptobioz** [comment]
Thanks for the PR!

Everything looks good to me but I have one question : are you sure the default Docker network mode should be "bridge"?

**Comment by majklovec** [comment]
Yes I am: https://docs.docker.com/network/network-tutorial-standalone/#use-the-default-bridge-network

**Comment by cryptobioz** [comment]
Ok, that's fine, thanks. Could you please fix the tests before we merge this?

**Comment by majklovec** [comment]
@cryptobioz I'd like to, but I'm sorry, but I have no idea how :(

**Comment by cryptobioz** [comment]
No problem, I'll do it.

**Comment by cryptobioz** [comment]
Thank you very much @majklovec for this new feature!

**Comment by majklovec** [comment]
You're welcome. I thank you @cryptobioz  for the rest of the software :) It's a cool one.

**Pull request merged**
