### PR TITLE
Allow setting a custom backup interval

### PR DESCRIPTION
**Pull request by cryptobioz**
This PR should fix the issue #295.

### CODE REVIEW

**Comment by LongJeongS** [comment]
How do we set the backup interval on startup? I dont see it documented in the README.md

**Comment by cryptobioz** [comment]
You can either set the environment variable `BIVAC_BACKUP_INTERVAL` or use the command line argument `backup.interval`. The default value is `23h`.

**Comment by LongJeongS** [comment]
Ah got it, thanks! Is this deployed as part of the 2.2.0  docker image or just the latest one?

**Comment by cryptobioz** [comment]
This feature is only available in the latest image as we didn't release any new version since.

**Pull request merged**
