### PR TITLE
Feature/restore

### PR DESCRIPTION
**Pull request by codejamninja**
I've already started the process of creating restore capabilities. This will fix the following issue.

#272
#118
#282

### CODE REVIEW

**Comment by codejamninja** [comment]
Below is the proposed cmd interface

```sh
Restore volumes

Usage:
  bivac restore [VOLUME_NAME] [flags]

Flags:
      --force                   Force restore by removing locks.
  -h, --help                    help for restore
      --remote.address string   Address of the remote Volback server. [VOLBACK_REMOTE_ADDRESS] (default "http://127.0.0.1:8182")
      --server.psk string       Pre-shared key. [VOLBACK_SERVER_PSK]
  -s, --snapshot string         Name of snapshot to restore (default "latest")

Global Flags:
  -b, --blacklist string   Do not backup blacklisted volumes. [BIVAC_VOLUMES_BLACKLIST]
  -v, --verbose            Enable verbose output [BIVAC_VERBOSE]
```

**Comment by mcanevet** [comment]
@cryptobioz isn't it already possible to restore using the `bivac restic -- restore ...` command?

**Comment by codejamninja** [comment]
No, that does not handle merging the directories, and it puts the files in the wrong location. It’s also not intuitive for users. Plus, it won’t work for databases that have been dumped. For example, a mongo database would need to run ‘mongorestore’.

Silly questions like this are part of the reason I originally decided to fork this project. I need this to work, and if you aren’t willing to support my pull request then then I have no choice but to fork it.

**Comment by mcanevet** [comment]
OK, sounds legit.
@codejamninja tests are failing, can you please fix?
@cryptobioz @raphink any opinion regarding the implementation? It looks like it can't break what exist, so at worst the restore feature may not exactly work as expected, but it should not have any impact on the backup feature. So it's OK for me to merge this and mark it as "experimental" in a future v2.1 release (once the unit tests are fixed off course).

**Comment by codejamninja** [comment]
Cool, I'll fix the unit tests

**Comment by codejamninja** [comment]
I find it odd that I can't reproduce the linting errors on my local machine.

Travis is sending the following linting error.
```
internal/utils/utils.go:76:20: undefined: strings.ReplaceAll
internal/utils/utils.go:93:20: undefined: strings.ReplaceAll
internal/utils/utils.go:134:18: undefined: strings.ReplaceAll
```

However, looking at the code, strings is most definitely in the scope.
https://github.com/codejamninja/bivac/blob/feature/restore/internal/utils/utils.go#L10

And, looking at the godocs, ReplaceAll is definitely a function available to strings.
https://golang.org/pkg/strings/#ReplaceAll

What's even stranger is that I have the identical code in the `engine.go` file, and the same linter doesn't complain about it.
https://github.com/codejamninja/bivac/blob/feature/restore/internal/engine/engine.go#L169

**Comment by codejamninja** [comment]
I've now added logic for subpaths in this commit. Issue #282

**Comment by mcanevet** [comment]
@codejamninja are you finished committing new stuffs in this PR? We are going to review this soon and merge it as experimental for the v2.1 if we think that it can't break anything in what exists.
Could you please rebase?

**Comment by codejamninja** [comment]
@mcanevet, absolutely. I'll go through it and get it done sometime this week.

**Comment by codejamninja** [comment]
Probably the part of this code that has the most likelihood of backwards compatibility issues is handing kubernetes subpaths. It might be best to first add support for the kubernetes subpaths, and test it, before accepting this pull request.

I will try and create a pull request for kubernetes subpath support separately.

**Comment by cryptobioz** [comment]
Thanks for the work @codejamninja!

**Comment by codejamninja** [comment]
Thanks for accepting it @cryptobioz

**Comment by LongJeongS** [comment]
@codejamninja is the usage simply `bivac restore x` ?

**Comment by codejamninja** [comment]
@LongJeongS correct

**Comment by codejamninja** [comment]
@LongJeongS please feel free to file any issues you have. It's a new feature and though it's been tested it potentially has bugs.

**Pull request merged**
