### PR TITLE
[orchestrator/docker] Forward manager volumes to worker

### LINKED ISSUE #176: Can't backup to filesystem?
Hi,

Running on the latest of bivac through the docker container, I wanted to backup some volumes to my USB disk, with something like:

```
sudo docker run --rm -ti --name bivac -v /var/run/docker.sock:/var/run/docker.sock:ro -v type=bind,source=/mnt/usb35/docker_backups,target=/docker_backups -e RESTIC_PASSWORD="backups" -e BIVAC_LOG_LEVEL=debug -e BIVAC_TARGET_URL=/docker_backups camp
tocamp/bivac
```

However, that does not seem to work. Permissions on the target directory can be as open as 777, and while restic says it inits the backup directory, there is nothing in there.

Is that normal? I know the README only mentioned S3, but the underlying tools allowing a myriad of backends, I thought that it might have been possible.

Thank you.

```
docker --version                                                                  
Docker version 18.03.1-ce, build 9ee9f40
```

```
INFO[0000] Detecting provider                            volume=graylog24_es_data                                              
DEBU[0000] Image already pulled, not pulling             image=busybox                                                         
DEBU[0000] Creating container                            command="sh -c ([[ -d /var/lib/docker/volumes/graylog24_es_data/_data/
mysql ]] && echo -n 'mysql') || ([[ -f /var/lib/docker/volumes/graylog24_es_data/_data/PG_VERSION ]] && echo -n 'postgresql') |
| ([[ -f /var/lib/docker/volumes/graylog24_es_data/_data/DB_CONFIG ]] && echo -n 'openldap'); return 0" environment= image=busy
box                                                                                                                            
DEBU[0001] Launching with 'sh -c ([[ -d /var/lib/docker/volumes/graylog24_es_data/_data/mysql ]] && echo -n 'mysql') || ([[ -f 
/var/lib/docker/volumes/graylog24_es_data/_data/PG_VERSION ]] && echo -n 'postgresql') || ([[ -f /var/lib/docker/volumes/graylo
g24_es_data/_data/DB_CONFIG ]] && echo -n 'openldap'); return 0'...                                                            
DEBU[0002]                                                                                                                     
DEBU[0002] Removing container                            container=13d242d77134bf77b018861000414586d51679da2e44c43a0c8b606bb37c
5fc6                                                                                                                           
INFO[0003] Found data provider                           provider=Default volume=graylog24_es_data                             
DEBU[0003] engine=restic                                                                                                       
INFO[0003] Found backup engine                           engine=Restic volume=graylog24_es_data                                
DEBU[0003] Image already pulled, not pulling             image="restic/restic:latest"                                          
DEBU[0003] Creating container                            command="-r /docker_backups/graylog24_es_data snapshots --no-cache" en
vironment="OS_REGION_NAME=, RESTIC_PASSWORD=backups, AWS_ACCESS_KEY_ID=, AWS_SECRET_ACCESS_KEY=, OS_USERNAME=, OS_PASSWORD=, OS
_AUTH_URL=, OS_TENANT_NAME=" image="restic/restic:latest"                                                                      
DEBU[0004] Launching with '-r /docker_backups/graylog24_es_data snapshots --no-cache'...                                       
DEBU[0006]  Fatal: unable to open config file: Stat: stat /docker_backups/graylog24_es_data/config: no such file or directory
 Is there a repository at the following location?
 /docker_backups/graylog24_es_data

DEBU[0006] Removing container                            container=8165fee639a2a3ee9e0bdb18dbbb735a75e26436c8c6b768bc03c6999f31
40b2
DEBU[0006] Image already pulled, not pulling             image="restic/restic:latest"
DEBU[0006] Creating container                            command="-r /docker_backups/graylog24_es_data init --no-cache" environ
ment="OS_AUTH_URL=, OS_TENANT_NAME=, OS_REGION_NAME=, RESTIC_PASSWORD=backups, AWS_ACCESS_KEY_ID=, AWS_SECRET_ACCESS_KEY=, OS_U
SERNAME=, OS_PASSWORD=" image="restic/restic:latest"
DEBU[0008] Launching with '-r /docker_backups/graylog24_es_data init --no-cache'...
DEBU[0011]  created restic repository c5eb85e2de at /docker_backups/graylog24_es_data

 Please note that knowledge of your password is required to access
 the repository. Losing your password means that your data is
 irrecoverably lost.

DEBU[0011] Removing container                            container=511a84c4cad4a58f4a6585e3f33d5e2a7458678a07ff5b881eb7a1265838
3dc3
DEBU[0012] Image already pulled, not pulling             image="restic/restic:latest"
DEBU[0012] Creating container                            command="--hostname f042a210db86 -r /docker_backups/graylog24_es_data
backup /var/lib/docker/volumes/graylog24_es_data/_data/ --no-cache" environment="OS_AUTH_URL=, OS_TENANT_NAME=, OS_REGION_NAME=
, RESTIC_PASSWORD=backups, AWS_ACCESS_KEY_ID=, AWS_SECRET_ACCESS_KEY=, OS_USERNAME=, OS_PASSWORD=" image="restic/restic:latest"
DEBU[0013] Launching with '--hostname f042a210db86 -r /docker_backups/graylog24_es_data backup /var/lib/docker/volumes/graylog2
4_es_data/_data/ --no-cache'...
DEBU[0015]  Fatal: unable to open config file: Stat: stat /docker_backups/graylog24_es_data/config: no such file or directory
 Is there a repository at the following location?
 /docker_backups/graylog24_es_data

DEBU[0015] Removing container                            container=39719c779813895ce19518a5575784fd8021a5a293a61ef8e093936a849c
eb9f
INFO[0018] retrying...
DEBU[0018] Image already pulled, not pulling             image="restic/restic:latest"
DEBU[0018] Creating container                            command="--hostname f042a210db86 -r /docker_backups/graylog24_es_data
backup /var/lib/docker/volumes/graylog24_es_data/_data/ --no-cache" environment="OS_REGION_NAME=, RESTIC_PASSWORD=backups, AWS_
ACCESS_KEY_ID=, AWS_SECRET_ACCESS_KEY=, OS_USERNAME=, OS_PASSWORD=, OS_AUTH_URL=, OS_TENANT_NAME=" image="restic/restic:latest"
DEBU[0019] Launching with '--hostname f042a210db86 -r /docker_backups/graylog24_es_data backup /var/lib/docker/volumes/graylog2
4_es_data/_data/ --no-cache'...
DEBU[0020]  Fatal: unable to open config file: Stat: stat /docker_backups/graylog24_es_data/config: no such file or directory
 Is there a repository at the following location?
 /docker_backups/graylog24_es_data
[...]
ERRO[0026] Failed to backup volume graylog24_es_data: failed to backup volume: failed to backup the volume: after 3 attempts, last error: Restic exited with state 1 while backuping the volume
```

### PR DESCRIPTION
**Pull request by mcanevet**
Fixes #176

### CODE REVIEW

**Comment by bbinet** [comment]
Thanks @mcanevet for your patch: I can now easily backup my local docker volume, that is great!

**Comment by bbinet** [comment]
BTW, when I backup data volume, bivac seems to create an intermediate directory which name is the bivac container id.
Do you know if I can configure bivac not to create this directory so that if I drop the current bivac container and create a new one with the same restic target url, it will use the same restic repositories as the previous container instead of creating new ones in a new intermediate <container_id> directory?

**Comment by mcanevet** [comment]
This is managed by `--restic-args` which defaults to `-r %B/%P/%V` with `%P` meaning the current container hostname in your case. So you can override this by setting `--restic-args="-r %B/%V"`.

**Comment by bbinet** [comment]
I think it should drop that <container_id> intermediate directory if I run my bivac container with `-e RESTIC_COMMON_ARGS="%B/%V"`, but then it fails at the restic "init" step (no specific error, but bivac is retrying the init step 3 times before giving up).
```
$ docker run --rm -ti -v /var/run/docker.sock:/var/run/docker.sock:ro -v /home/bruno/backups:/home/bruno/backups -e RESTIC_PASSWORD="backups" -e RESTIC_DOCKER_IMAGE=restic/restic:0.9.3 -e BIVAC_TARGET_URL=/home/bruno/backups -e RESTIC_COMMON_ARGS="%B/%V" -e BIVAC_LOG_LEVEL=debug camptocamp/bivac:1.0.0-alpha8
INFO[0000] Bivac v1.0.0-alpha8-dirty starting backup... 
DEBU[0000] Detecting orchestrator based on environment... 
DEBU[0000] Using orchestrator: Docker                   
INFO[0000] Ignoring volume                               reason=unnamed source= volume=45e3ca259859b878cc8ad1e0c1d760536d879ea8e373d1100e15acc60b1814cd
DEBU[0000] Adding event                                  event="bivac_backupStartTime{volume=\"saltstack_saltmaster-states\"} 1542185501" metric=bivac_backupStartTime
DEBU[0000] No Pushgateway URL specified, not pushing metrics 
DEBU[0000] Running detection command in container 2ec5c3f916f949f02d83d3f95cd00c983550c36d576dd82dbff1ea5b05119162...  cmd="([[ -d /srv/setupify/states/mysql ]] && echo 'mysql') || ([[ -f /srv/setupify/states/PG_VERSION ]] && echo 'postgresql') || ([[ -f /srv/setupify/states/DB_CONFIG ]] && echo 'openldap') || true" volume=saltstack_saltmaster-states
DEBU[0000] engine=restic                                
INFO[0000] Found backup engine                           engine=Restic volume=saltstack_saltmaster-states
DEBU[0000] Replacing args, Input: [snapshots --no-cache %B/%V] 
DEBU[0000] Replacing args, Output: [snapshots --no-cache /home/bruno/backups/saltstack_saltmaster-states] 
DEBU[0000] Image already pulled, not pulling             image="restic/restic:0.9.3"
DEBU[0000] Creating container                            command="snapshots --no-cache /home/bruno/backups/saltstack_saltmaster-states" environment="RESTIC_PASSWORD=backups, RESTIC_DOCKER_IMAGE=restic/restic:0.9.3, BIVAC_TARGET_URL=/home/bruno/backups, RESTIC_COMMON_ARGS=%B/%V, BIVAC_LOG_LEVEL=debug, PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" image="restic/restic:0.9.3" mounts="[{bind /home/bruno/backups /home/bruno/backups false <nil> <nil> <nil>} {bind /var/run/docker.sock /var/run/docker.sock true <nil> <nil> <nil>}]"
DEBU[0000] Launching with 'snapshots --no-cache /home/bruno/backups/saltstack_saltmaster-states'... 
DEBU[0002] Removing container                            container=66689c6aaf2e930297b318948f3317f98c222e55ca822c5e51a5d6fc99cc75b1
DEBU[0002] Replacing args, Input: [init --no-cache %B/%V] 
DEBU[0002] Replacing args, Output: [init --no-cache /home/bruno/backups/saltstack_saltmaster-states] 
DEBU[0002] Image already pulled, not pulling             image="restic/restic:0.9.3"
DEBU[0002] Creating container                            command="init --no-cache /home/bruno/backups/saltstack_saltmaster-states" environment="RESTIC_PASSWORD=backups, RESTIC_DOCKER_IMAGE=restic/restic:0.9.3, BIVAC_TARGET_URL=/home/bruno/backups, RESTIC_COMMON_ARGS=%B/%V, BIVAC_LOG_LEVEL=debug, PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" image="restic/restic:0.9.3" mounts="[{volume saltstack_saltmaster-states /media/docker/volumes/saltstack_saltmaster-states/_data false <nil> <nil> <nil>} {bind /home/bruno/backups /home/bruno/backups false <nil> <nil> <nil>} {bind /var/run/docker.sock /var/run/docker.sock true <nil> <nil> <nil>}]"
DEBU[0002] Launching with 'init --no-cache /home/bruno/backups/saltstack_saltmaster-states'... 
DEBU[0003] Removing container                            container=949d7bfd6a028bb86769220485cd5529b7b441826fe0f1ccb2754428d4be9a87
INFO[0006] retrying...                                  
DEBU[0006] Replacing args, Input: [snapshots --no-cache %B/%V] 
DEBU[0006] Replacing args, Output: [snapshots --no-cache /home/bruno/backups/saltstack_saltmaster-states] 
DEBU[0006] Image already pulled, not pulling             image="restic/restic:0.9.3"
DEBU[0006] Creating container                            command="snapshots --no-cache /home/bruno/backups/saltstack_saltmaster-states" environment="RESTIC_PASSWORD=backups, RESTIC_DOCKER_IMAGE=restic/restic:0.9.3, BIVAC_TARGET_URL=/home/bruno/backups, RESTIC_COMMON_ARGS=%B/%V, BIVAC_LOG_LEVEL=debug, PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" image="restic/restic:0.9.3" mounts="[{bind /var/run/docker.sock /var/run/docker.sock true <nil> <nil> <nil>} {bind /home/bruno/backups /home/bruno/backups false <nil> <nil> <nil>}]"
DEBU[0006] Launching with 'snapshots --no-cache /home/bruno/backups/saltstack_saltmaster-states'... 
DEBU[0008] Removing container                            container=19912847781b912a089f4c03fbab825fdfc06bc0004513c2ca51b775cf515f3f
DEBU[0008] Replacing args, Input: [init --no-cache %B/%V] 
DEBU[0008] Replacing args, Output: [init --no-cache /home/bruno/backups/saltstack_saltmaster-states] 
DEBU[0008] Image already pulled, not pulling             image="restic/restic:0.9.3"
DEBU[0008] Creating container                            command="init --no-cache /home/bruno/backups/saltstack_saltmaster-states" environment="RESTIC_PASSWORD=backups, RESTIC_DOCKER_IMAGE=restic/restic:0.9.3, BIVAC_TARGET_URL=/home/bruno/backups, RESTIC_COMMON_ARGS=%B/%V, BIVAC_LOG_LEVEL=debug, PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" image="restic/restic:0.9.3" mounts="[{volume saltstack_saltmaster-states /media/docker/volumes/saltstack_saltmaster-states/_data false <nil> <nil> <nil>} {bind /home/bruno/backups /home/bruno/backups false <nil> <nil> <nil>} {bind /var/run/docker.sock /var/run/docker.sock true <nil> <nil> <nil>}]"
DEBU[0008] Launching with 'init --no-cache /home/bruno/backups/saltstack_saltmaster-states'... 
DEBU[0010] Removing container                            container=eefc91edcecd2fbfa1cf5f29fcb1aea0fd0c184f1237e1fc22deaca5dd174974
INFO[0012] retrying...                                  
DEBU[0012] Replacing args, Input: [snapshots --no-cache %B/%V] 
DEBU[0012] Replacing args, Output: [snapshots --no-cache /home/bruno/backups/saltstack_saltmaster-states] 
DEBU[0012] Image already pulled, not pulling             image="restic/restic:0.9.3"
DEBU[0012] Creating container                            command="snapshots --no-cache /home/bruno/backups/saltstack_saltmaster-states" environment="RESTIC_PASSWORD=backups, RESTIC_DOCKER_IMAGE=restic/restic:0.9.3, BIVAC_TARGET_URL=/home/bruno/backups, RESTIC_COMMON_ARGS=%B/%V, BIVAC_LOG_LEVEL=debug, PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" image="restic/restic:0.9.3" mounts="[{bind /home/bruno/backups /home/bruno/backups false <nil> <nil> <nil>} {bind /var/run/docker.sock /var/run/docker.sock true <nil> <nil> <nil>}]"
DEBU[0012] Launching with 'snapshots --no-cache /home/bruno/backups/saltstack_saltmaster-states'... 
DEBU[0014] Removing container                            container=d852916a6f5d44590d51a6a727645b248c4f7c1d7008b847bb668cb49010b917
DEBU[0014] Replacing args, Input: [init --no-cache %B/%V] 
DEBU[0014] Replacing args, Output: [init --no-cache /home/bruno/backups/saltstack_saltmaster-states] 
DEBU[0014] Image already pulled, not pulling             image="restic/restic:0.9.3"
DEBU[0014] Creating container                            command="init --no-cache /home/bruno/backups/saltstack_saltmaster-states" environment="RESTIC_PASSWORD=backups, RESTIC_DOCKER_IMAGE=restic/restic:0.9.3, BIVAC_TARGET_URL=/home/bruno/backups, RESTIC_COMMON_ARGS=%B/%V, BIVAC_LOG_LEVEL=debug, PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" image="restic/restic:0.9.3" mounts="[{volume saltstack_saltmaster-states /media/docker/volumes/saltstack_saltmaster-states/_data false <nil> <nil> <nil>} {bind /home/bruno/backups /home/bruno/backups false <nil> <nil> <nil>} {bind /var/run/docker.sock /var/run/docker.sock true <nil> <nil> <nil>}]"
DEBU[0014] Launching with 'init --no-cache /home/bruno/backups/saltstack_saltmaster-states'... 
DEBU[0016] Removing container                            container=727333ee681002f34cbe85db53d1105c12aa576f50402d0ce072e83701e64140
DEBU[0016] Adding event                                  event="bivac_backupExitCode{volume=\"saltstack_saltmaster-states\"} 1" metric=bivac_backupExitCode
DEBU[0016] Adding event                                  event="bivac_backupEndTime{volume=\"saltstack_saltmaster-states\"} 1542185517" metric=bivac_backupEndTime
DEBU[0016] No Pushgateway URL specified, not pushing metrics 
ERRO[0016] Failed to backup volume saltstack_saltmaster-states: failed to backup volume: failed to create a secure repository: after 3 attempts, last error: Restic exited with state 1 while initializing the repository
```
@mcanevet @raphink any idea?

**Comment by bbinet** [comment]
Sorry, my bad, it should be: `-e RESTIC_COMMON_ARGS="-r %B/%V"`
Now it works perfectly!

**Pull request merged**
